### ISSUE TITLE
RT alignment error - resolved

### ISSUE THREAD

**Issue by vplekhov** [pablovgd/TARDIS#4]
Hi all, 

I ran into an error during the RT alignment step (see screenshot) 
![Screenshot 2024-09-24 at 13 21 33 (2)](https://github.com/user-attachments/assets/8726ae65-50f3-4d5b-9cc4-944a9ff752c0)
The issue turned out to be due to a couple of corrupted raw MS files (probably MS acquisition error, leaving the files too small compared to others run with the same MS method). After excluding the corrupted files everything worked perfectly.

Hope this helps if anyone else runs into the same problem! :)

**Comment by pablovgd** [comment]
Hi!

Thanks for reporting this :) I'll have to include some kind of check so a clear error message gets displayed when this happens. Could you send me one of those files?

**Comment by vplekhov** [comment]
Absolutely! The link to the files should be in your mailbox already
